package edu.sjsu.team408.parkhere;

import android.support.test.runner.AndroidJUnit4;
import android.test.ActivityUnitTestCase;

import com.google.android.gms.maps.model.LatLng;

import org.junit.Test;
import org.junit.runner.RunWith;

/**
 * Created by DuocNguyen on 11/9/17.
 */
@RunWith(AndroidJUnit4.class)
public class AddressClassTest  extends ActivityUnitTestCase<MainActivity> {
    public AddressClassTest(){
        super(MainActivity.class);
    }


    /**
     * Test the formatAddress function in Address Class
     * Providing expectedAdress comparing with formatAddress function Address object
     */
    @Test
    public void formatAddressTest1() {
        String streetAddress = "2770 Bristol Dr";
        String city = "San Jose";
        String state = "CA";
        String zipCode = "95127";
        double latitude = 0;
        double longitude = 0;

        Address expectedAddress = new Address(streetAddress, city, state, zipCode, latitude, longitude);
        Address actual = new Address();

        String fullStreetAddress = "2770 Bristol Dr, San Jose, CA 95127";

        actual.formatAddress(fullStreetAddress, null);
        assertEquals(expectedAddress, actual);
    }


    /**
     * Test the formatAdress function in Address class
     * Providing an empty Address object as expected value.
     * Comparing with empty Address object generated by formatAddress function.
     */
    @Test
    public void formatAddressTest2() {
        String streetAddress = "";
        String city = "";
        String state = "";
        String zipCode = "";
        double latitude = 0;
        double longitude = 0;

        Address expectedAddress = new Address(streetAddress, city, state, zipCode, latitude, longitude);
        Address actual = new Address();

        String fullStreetAddress = "";  //empty street address should return Address object with no attributes

        actual.formatAddress(fullStreetAddress, null);
        assertEquals(expectedAddress, actual);
    }

    /**
     * Test toString method for correct format address
     */
    @Test
    public void toStringTest1() {
        String fullAddress = "2770 Bristol Dr, San Jose, CA 95127";
        Address a = new Address(fullAddress, null);
        assertEquals(fullAddress, a.toString());
    }

    /**
     * Test toString method for correct format address
     * This should return empty string since there is an incorrect address
     */
    @Test
    public void toStringTest2() {
        String fullAddress = "2770 Bristol Dr, CA 95127";   //missing City
        Address a = new Address(fullAddress, null);
        assertEquals("", a.toString());
    }


}
